name: don-macaron
options:
  bundleIdPrefix: com.myapp
targets:
  don-macaron:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [don-macaron]
    depencencies:
      - sdk: Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework

