name: don-macaron
options:
  bundleIdPrefix: com.myapp
targets:
  don-macaron:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [don-macaron]
  don-macaronTests:
    type: framework
    platform: iOS
    sources: [don-macaronTests]

